stages:
  - test
  - name: deploy
    if: branch = master AND type = push AND fork = false
jobs:
  include:
    - stage: test
      sudo: required
      services: docker
      os: linux
      script:
        - docker build -t christianmoesl/lms-wasm .
        - docker run christianmoesl/lms-wasm sbt test
    - stage: deploy
      sudo: required
      services: docker
      os: linux
      script:
        - docker build -t christianmoesl/lms-wasm .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push christianmoesl/lms-wasm
notifications:
  email: false
  slack:
    rooms:
      - rompfgroup:rt1C65fF6zd0w8KMpRo5dM4K#lms-wasm
    on_success: change
    on_failure: always