name: Release

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Build
      run: docker build -t christianmoesl/lms-wasm .
    
    - name: Update DockerHub Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u christianmoesl --password-stdin
        docker push christianmoesl/lms-wasm
